export const products = [
  {
    id: 1,
    categoryName: 'Electronics',
    products: [
      {
        id: 'ELECTRONIC_PRODUCT_1',
        img: 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/a/b/0/-original-imaghx9qnhzxegu2.jpeg?q=70',
        name: 'Mobile',
        description: 'This is mobile',
        quantity: 0,
        price: 12000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_2',
        name: 'Laptop',
        description: 'This is Laptop',
        quantity: 0,
        price: 120000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_3',
        name: 'Tablet',
        description: 'This is Tablet',
        quantity: 0,
        price: 30000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_4',
        name: 'Smartwatch',
        description: 'This is Smartwatch',
        quantity: 0,
        price: 15000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_5',
        name: 'Headphones',
        description: 'These are Headphones',
        quantity: 0,
        price: 5000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_6',
        name: 'Camera',
        description: 'This is Camera',
        quantity: 0,
        price: 45000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_7',
        name: 'Printer',
        description: 'This is Printer',
        quantity: 0,
        price: 20000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_8',
        name: 'Monitor',
        description: 'This is Monitor',
        quantity: 0,
        price: 10000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_9',
        name: 'Keyboard',
        description: 'This is Keyboard',
        quantity: 0,
        price: 2000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_10',
        name: 'Mouse',
        description: 'This is Mouse',
        quantity: 0,
        price: 1000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_11',
        name: 'Speaker',
        description: 'This is Speaker',
        quantity: 0,
        price: 8000,
      },
      {
        id: 'ELECTRONIC_PRODUCT_12',
        name: 'Router',
        description: 'This is Router',
        quantity: 0,
        price: 3000,
      },
    ],
  },
  {
    id: 2,
    categoryName: 'Kitchen',
    products: [
      {
        id: 'KITCHEN_PRODUCT_1',
        name: 'Spoon',
        description: 'This is Spoon',
        quantity: 0,
        price: 150,
      },
      {
        id: 'KITCHEN_PRODUCT_2',
        name: 'Gas Stoves',
        description: 'This is Gas Stoves',
        quantity: 0,
        price: 2500,
      },
      {
        id: 'KITCHEN_PRODUCT_3',
        name: 'Water bottles',
        description: 'This is Water bottles',
        quantity: 0,
        price: 800,
      },
    ],
  },
  {
    id: 3,
    categoryName: 'Furniture',
    products: [
      {
        id: 'FURNITURE_PRODUCT_1',
        name: 'Office Chairs',
        description: 'This is Office Chairs',
        quantity: 0,
        price: 650,
      },
    ],
  },
  {
    id: 4,
    categoryName: 'Other',
    products: [],
  },
];
